[workspace]

resolver = "2"
members = [
  "toolkit",
  "day-0-cookie-cutter",
  "day-1-trebuchet",
  "day-2-cubes",
  "day-3-gears",
  "day-4-scratch-cards",
  "day-5-seeds",
  "day-6-boat-race",
  "day-7-camel-card",
]
